version: 0.2

phases:
  install:
    commands:
      - echo "Installing frontend dependencies..."
      - cd client
      - npm install

  build:
    commands:
      - echo "Building React frontend..."
      - echo "VITE_API_URL=/api" > .env
      - npm run build

  post_build:
    commands:
      - echo "Preparing frontend deployment artifact..."
      - cd ..
      - mkdir -p artifact/frontend
      - cp -r client/dist/* artifact/frontend/
      - cp deploy/frontend/appspec.yml artifact/appspec.yml
      - cp -r deploy/frontend/scripts artifact/scripts

artifacts:
  base-directory: artifact
  files:
    - "**/*"
